//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface CropSettings
{
	x1: number;
	y1: number;
	x2: number;
	y2: number;
}
