//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum ScaleMode { 
	Default = 0, 
	Max = 1, 
	Pad = 2, 
	Crop = 3, 
	Carve = 4, 
	Stretch = 5
}
